name: tvc-games
version: 0.1.0
category: game
license: GPL-3

extra-source-files:
  - README.md

dependencies:
  - base
  - z80
  - bytestring
  - filepath
  - directory
  - JuicyPixels
  - lens
  - split

source-dirs:
  - src

executables:
  homelab-games:
    main: main.hs
